export const UI_TEXT = {
  it: {
    home: {
      title: "Live Games Hub",
      subtitle: "Scegli il gioco da usare in live",
      languageLabel: "Lingua",
      open: "Apri",
      backToMenu: "← Torna al menu",
    },
    games: {
      hangmanTitle: "Impiccato",
      hangmanDesc: "Indovina la parola o frase con un indizio",
      hangmanIcon: "🤖",
      hangmanIconBg: "from-emerald-400 to-lime-500",
      hangmanOverlay: "from-emerald-500/20 via-transparent to-lime-500/20",

      secretwordTitle: "Parola Segreta",
      secretwordDesc: "Trova la parola con tentativi limitati",
      secretwordIconBg: "from-cyan-400 to-fuchsia-500",
      secretwordOverlay: "from-fuchsia-500/20 via-transparent to-cyan-500/20",
      secretwordIconCells: ["bg-green-500", "bg-yellow-400", "bg-slate-500"],

      numbergameTitle: "Indovina il Numero",
      numbergameDesc: "Più alto, più basso… trova il numero segreto!",
      numbergameIconBg: "from-orange-400 to-yellow-400",
      numbergameOverlay: "from-orange-500/20 via-transparent to-yellow-500/20",

      mastermindTitle: "Mastermind",
      mastermindDesc: "Indovina la combinazione di colori",
      mastermindIconBg: "from-violet-400 to-pink-500",
      mastermindOverlay: "from-violet-500/20 via-transparent to-pink-500/20",
      mastermindIconDots: ["bg-red-500", "bg-blue-500", "bg-green-500", "bg-yellow-400"],
    },
    hangman: {
      restart: "Ricomincia",
      random: "Casuale",
      import: "Importa",
      fullscreenEnter: "Full",
      fullscreenExit: "Esci",
      soundOn: "On",
      soundOff: "Off",
      showPanels: "Mostra pannelli",
      hidePanels: "Nascondi pannelli",
      clue: "Indizio",
      try: "Prova",
      showSolution: "Mostra soluzione",
      hideSolution: "Nascondi soluzione",
      letterPlaceholder: "Lettera",
      longLetterPlaceholder: "Inserisci una lettera",
      errors: "Errori",
      won: "Vinto",
      lost: "Perso",
      easy: "Facile",
      medium: "Media",
      hard: "Difficile",
      hearts: "Cuori",
      addItemTitle: "Aggiungi parola o frase",
      itemPlaceholder: "Parola o frase",
      cluePlaceholder: "Indizio",
      addAndPlay: "Aggiungi e gioca",
      archiveTitle: "Archivio live",
      roundLabel: "Round",
      hiddenSolution: "soluzione nascosta",
      liveGame: "Gioco stile live",
      title: "Indovina la parola o la frase",
      downloadTemplate: "Scarica template",
      next: "Avanti",
    },
    secretword: {
      title: "Parola Segreta",
      subtitle: "Indovina la parola",
      restart: "Reset",
      random: "Casuale",
      next: "Avanti",
      length: "Lunghezza",
      lengthLabel: "Lunghezza",
      attempts: "Tentativi",
      won: "Hai indovinato",
      lost: "Parola",
    },
    mastermind: {
      won: "Hai vinto 🎉",
      lost: "Hai perso 😈",
      solution: "Soluzione",
      next: "Avanti",
      colors: "Colori",
    },
    numbergame: {
      title: "Indovina il Numero",
      reset: "Reset",
      setupDesc: "Scegli il range dei numeri per questo round",
      from: "Da",
      to: "A",
      attemptsInfo: "Tentativi:",
      start: "🎲 Inizia il round!",
      range: "Range",
      won: "🎉 Trovato!",
      wonIn: "In",
      attempts: "tentativi",
      lost: "😈 Tempo scaduto!",
      solution: "Era il",
      nextRound: "Nuovo round",
      changeRange: "Cambia range",
    },
  },

  en: {
    home: {
      title: "Live Games Hub",
      subtitle: "Choose the game to use on live",
      languageLabel: "Language",
      open: "Open",
      backToMenu: "← Back to menu",
    },
    games: {
      hangmanTitle: "Hangman",
      hangmanDesc: "Guess the word or phrase with a clue",
      hangmanIcon: "🤖",
      hangmanIconBg: "from-emerald-400 to-lime-500",
      hangmanOverlay: "from-emerald-500/20 via-transparent to-lime-500/20",

      secretwordTitle: "Secret Word",
      secretwordDesc: "Find the word with limited attempts",
      secretwordIconBg: "from-cyan-400 to-fuchsia-500",
      secretwordOverlay: "from-fuchsia-500/20 via-transparent to-cyan-500/20",
      secretwordIconCells: ["bg-emerald-600", "bg-yellow-400", "bg-slate-500"],

      numbergameTitle: "Guess the Number",
      numbergameDesc: "Higher, lower… find the secret number!",
      numbergameIconBg: "from-orange-400 to-yellow-400",
      numbergameOverlay: "from-orange-500/20 via-transparent to-yellow-500/20",

      mastermindTitle: "Mastermind",
      mastermindDesc: "Guess the color combination",
      mastermindIconBg: "from-violet-400 to-pink-500",
      mastermindOverlay: "from-violet-500/20 via-transparent to-pink-500/20",
      mastermindIconDots: ["bg-red-500", "bg-blue-500", "bg-green-500", "bg-yellow-400"],
    },
    hangman: {
      restart: "Restart",
      random: "Random",
      import: "Import",
      fullscreenEnter: "Full",
      fullscreenExit: "Exit",
      soundOn: "On",
      soundOff: "Off",
      showPanels: "Show panels",
      hidePanels: "Hide panels",
      clue: "Clue",
      try: "Try",
      showSolution: "Show solution",
      hideSolution: "Hide solution",
      letterPlaceholder: "Letter",
      longLetterPlaceholder: "Enter a letter",
      errors: "Errors",
      won: "Won",
      lost: "Lost",
      easy: "Easy",
      medium: "Medium",
      hard: "Hard",
      hearts: "Hearts",
      addItemTitle: "Add word or phrase",
      itemPlaceholder: "Word or phrase",
      cluePlaceholder: "Clue",
      addAndPlay: "Add and play",
      archiveTitle: "Live archive",
      roundLabel: "Round",
      hiddenSolution: "hidden solution",
      liveGame: "Live style game",
      title: "Guess the word or phrase",
      downloadTemplate: "Download template",
      next: "Next",
    },
    secretword: {
      title: "Secret Word",
      subtitle: "Guess the word",
      restart: "Reset",
      random: "Random",
      next: "Next",
      length: "Length",
      lengthLabel: "Length",
      attempts: "Attempts",
      won: "You guessed it",
      lost: "Word",
    },
    mastermind: {
      won: "You won 🎉",
      lost: "You lost 😈",
      solution: "Solution",
      next: "Next",
      colors: "Colors",
    },
    numbergame: {
      title: "Guess the Number",
      reset: "Reset",
      setupDesc: "Choose the number range for this round",
      from: "From",
      to: "To",
      attemptsInfo: "Attempts:",
      start: "🎲 Start the round!",
      range: "Range",
      won: "🎉 Found it!",
      wonIn: "In",
      attempts: "attempts",
      lost: "😈 Time's up!",
      solution: "It was",
      nextRound: "Next round",
      changeRange: "Change range",
    },
  },

  ro: {
    home: {
      title: "Hub Jocuri Live",
      subtitle: "Alege jocul pentru live",
      languageLabel: "Limbă",
      open: "Deschide",
      backToMenu: "← Înapoi la meniu",
    },
    games: {
      hangmanTitle: "Ghicește cuvântul",
      hangmanDesc: "Joc cu indicii, inimi și tastatură interactivă",
      hangmanIcon: "🤖",
      hangmanIconBg: "from-emerald-400 to-lime-500",
      hangmanOverlay: "from-emerald-500/20 via-transparent to-lime-500/20",

      secretwordTitle: "Cuvânt Secret",
      secretwordDesc: "Ghicește cuvântul cu încercări limitate",
      secretwordIconBg: "from-cyan-400 to-fuchsia-500",
      secretwordOverlay: "from-fuchsia-500/20 via-transparent to-cyan-500/20",
      secretwordIconCells: ["bg-green-500", "bg-yellow-400", "bg-slate-500"],

      numbergameTitle: "Ghicește Numărul",
      numbergameDesc: "Mai mare, mai mic… găsește numărul secret!",
      numbergameIconBg: "from-orange-400 to-yellow-400",
      numbergameOverlay: "from-orange-500/20 via-transparent to-yellow-500/20",

      mastermindTitle: "Mastermind",
      mastermindDesc: "Ghicește combinația de culori",
      mastermindIconBg: "from-violet-400 to-pink-500",
      mastermindOverlay: "from-violet-500/20 via-transparent to-pink-500/20",
      mastermindIconDots: ["bg-red-500", "bg-blue-500", "bg-green-500", "bg-yellow-400"],
    },
    hangman: {
      restart: "Reia",
      random: "Aleator",
      import: "Importă",
      fullscreenEnter: "Tot ecranul",
      fullscreenExit: "Ieși",
      soundOn: "Pornit",
      soundOff: "Oprit",
      showPanels: "Arată panourile",
      hidePanels: "Ascunde panourile",
      clue: "Indiciu",
      try: "Încearcă",
      showSolution: "Arată soluția",
      hideSolution: "Ascunde soluția",
      letterPlaceholder: "Literă",
      longLetterPlaceholder: "Introdu o literă",
      errors: "Greșeli",
      won: "Câștigat",
      lost: "Pierdut",
      easy: "Ușor",
      medium: "Mediu",
      hard: "Dificil",
      hearts: "Inimi",
      addItemTitle: "Adaugă cuvânt sau expresie",
      itemPlaceholder: "Cuvânt sau expresie",
      cluePlaceholder: "Indiciu",
      addAndPlay: "Adaugă și joacă",
      archiveTitle: "Arhivă live",
      roundLabel: "Runda",
      hiddenSolution: "soluție ascunsă",
      liveGame: "Joc stil live",
      title: "Ghicește cuvântul sau expresia",
      downloadTemplate: "Descarcă șablonul",
      next: "Înainte",
    },
    secretword: {
      title: "Cuvânt Secret",
      subtitle: "Ghicește cuvântul",
      restart: "Reset",
      random: "Aleator",
      next: "Următor",
      length: "Lungime",
      lengthLabel: "Lungime",
      attempts: "Încercări",
      won: "Ai ghicit",
      lost: "Cuvântul",
    },
    mastermind: {
      won: "Ai câștigat 🎉",
      lost: "Ai pierdut 😈",
      solution: "Soluție",
      next: "Următor",
      colors: "Culori",
    },
    numbergame: {
      title: "Ghicește Numărul",
      reset: "Reset",
      setupDesc: "Alege intervalul de numere pentru această rundă",
      from: "De la",
      to: "La",
      attemptsInfo: "Încercări:",
      start: "🎲 Începe runda!",
      range: "Interval",
      won: "🎉 Găsit!",
      wonIn: "În",
      attempts: "încercări",
      lost: "😈 Timp expirat!",
      solution: "Era",
      nextRound: "Rundă nouă",
      changeRange: "Schimbă intervalul",
    },
  },

  fr: {
    home: {
      title: "Jeux en direct",
      subtitle: "Choisissez un jeu et jouez avec votre communauté",
      languageLabel: "Langue",
      open: "Ouvrir",
      backToMenu: "← Retour au menu",
    },
    games: {
      hangmanTitle: "Jeu du pendu",
      hangmanDesc: "Devinez le mot ou la phrase avec l'aide de l'indice",
      hangmanIcon: "🤖",
      hangmanIconBg: "from-emerald-400 to-lime-500",
      hangmanOverlay: "from-emerald-500/20 via-transparent to-lime-500/20",

      secretwordTitle: "Mot Secret",
      secretwordDesc: "Trouvez le mot avec des tentatives limitées",
      secretwordIconBg: "from-cyan-400 to-fuchsia-500",
      secretwordOverlay: "from-fuchsia-500/20 via-transparent to-cyan-500/20",
      secretwordIconCells: ["bg-green-500", "bg-yellow-400", "bg-slate-500"],

      numbergameTitle: "Devine le Nombre",
      numbergameDesc: "Plus haut, plus bas… trouve le nombre secret !",
      numbergameIconBg: "from-orange-400 to-yellow-400",
      numbergameOverlay: "from-orange-500/20 via-transparent to-yellow-500/20",

      mastermindTitle: "Mastermind",
      mastermindDesc: "Devinez la combinaison de couleurs",
      mastermindIconBg: "from-violet-400 to-pink-500",
      mastermindOverlay: "from-violet-500/20 via-transparent to-pink-500/20",
      mastermindIconDots: ["bg-red-500", "bg-blue-500", "bg-green-500", "bg-yellow-400"],
    },
    hangman: {
      restart: "Recommencer",
      random: "Aléatoire",
      import: "Importer",
      fullscreenEnter: "Plein écran",
      fullscreenExit: "Quitter",
      soundOn: "Son ON",
      soundOff: "Son OFF",
      showPanels: "Afficher panneaux",
      hidePanels: "Masquer panneaux",
      clue: "Indice",
      try: "Essayer",
      showSolution: "Afficher la solution",
      hideSolution: "Masquer la solution",
      letterPlaceholder: "Lettre",
      longLetterPlaceholder: "Entrez une lettre",
      errors: "Erreurs",
      won: "Gagné",
      lost: "Perdu",
      easy: "Facile",
      medium: "Moyen",
      hard: "Difficile",
      hearts: "Cœurs",
      addItemTitle: "Ajouter mot ou phrase",
      itemPlaceholder: "Mot ou phrase",
      cluePlaceholder: "Indice",
      addAndPlay: "Ajouter et jouer",
      archiveTitle: "Archives live",
      roundLabel: "Manche",
      hiddenSolution: "solution cachée",
      liveGame: "Jeu style live",
      title: "Devinez le mot ou la phrase",
      downloadTemplate: "Télécharger modèle",
      next: "Suivant",
    },
    secretword: {
      title: "Mot Secret",
      subtitle: "Devine le mot",
      restart: "Reset",
      random: "Aléatoire",
      next: "Suivant",
      length: "Longueur",
      lengthLabel: "Longueur",
      attempts: "Essais",
      won: "Trouvé",
      lost: "Mot",
    },
    mastermind: {
      won: "Vous avez gagné 🎉",
      lost: "Vous avez perdu 😈",
      solution: "Solution",
      next: "Suivant",
      colors: "Couleurs",
    },
    numbergame: {
      title: "Devine le Nombre",
      reset: "Reset",
      setupDesc: "Choisissez la plage de nombres pour ce round",
      from: "De",
      to: "À",
      attemptsInfo: "Essais :",
      start: "🎲 Commencer le round !",
      range: "Plage",
      won: "🎉 Trouvé !",
      wonIn: "En",
      attempts: "essais",
      lost: "😈 Temps écoulé !",
      solution: "C'était le",
      nextRound: "Nouveau round",
      changeRange: "Changer la plage",
    },
  },
};
