export const UI_TEXT = {
  it: {
    home: {
      title: "Live Games Hub",
      subtitle: "Scegli il gioco da usare in live",
      languageLabel: "Lingua",
      open: "Apri",
      backToMenu: "← Torna al menu",
    },
    games: {
      hangmanTitle: "Indovina la parola o la frase",
      hangmanDesc: "Gioco con indizi, cuori e tastiera interattiva",
    },
    hangman: {
      restart: "Ricomincia",
      random: "Casuale",
      import: "Importa",
      fullscreenEnter: "Full",
      fullscreenExit: "Esci",
      soundOn: "On",
      soundOff: "Off",
      showPanels: "Mostra pannelli",
      hidePanels: "Nascondi pannelli",
      clue: "Indizio",
      try: "Prova",
      showSolution: "Mostra soluzione",
      hideSolution: "Nascondi soluzione",
      letterPlaceholder: "Lettera",
      longLetterPlaceholder: "Inserisci una lettera",
      errors: "Errori",
      won: "Vinto",
      lost: "Perso",
      easy: "Facile",
      medium: "Media",
      hard: "Difficile",
      hearts: "Cuori",
      addItemTitle: "Aggiungi parola o frase",
      itemPlaceholder: "Parola o frase",
      cluePlaceholder: "Indizio",
      addAndPlay: "Aggiungi e gioca",
      archiveTitle: "Archivio live",
      roundLabel: "Round",
      hiddenSolution: "soluzione nascosta",
      liveGame: "Gioco stile live",
      title: "Indovina la parola o la frase",
      downloadTemplate: "Scarica template",
      next: "Avanti",
    },
  },

  en: {
    home: {
      title: "Live Games Hub",
      subtitle: "Choose the game to use on live",
      languageLabel: "Language",
      open: "Open",
      backToMenu: "← Back to menu",
    },
    games: {
      hangmanTitle: "Guess the word or phrase",
      hangmanDesc: "Game with clues, hearts and interactive keyboard",
    },
    hangman: {
      restart: "Restart",
      random: "Random",
      import: "Import",
      fullscreenEnter: "Full",
      fullscreenExit: "Exit",
      soundOn: "On",
      soundOff: "Off",
      showPanels: "Show panels",
      hidePanels: "Hide panels",
      clue: "Clue",
      try: "Try",
      showSolution: "Show solution",
      hideSolution: "Hide solution",
      letterPlaceholder: "Letter",
      longLetterPlaceholder: "Enter a letter",
      errors: "Errors",
      won: "Won",
      lost: "Lost",
      easy: "Easy",
      medium: "Medium",
      hard: "Hard",
      hearts: "Hearts",
      addItemTitle: "Add word or phrase",
      itemPlaceholder: "Word or phrase",
      cluePlaceholder: "Clue",
      addAndPlay: "Add and play",
      archiveTitle: "Live archive",
      roundLabel: "Round",
      hiddenSolution: "hidden solution",
      liveGame: "Live style game",
      title: "Guess the word or phrase",
      downloadTemplate: "Download template",
      next: "Next",
    },
  },

  ro: {
    home: {
      title: "Hub Jocuri Live",
      subtitle: "Alege jocul pentru live",
      languageLabel: "Limbă",
      open: "Deschide",
      backToMenu: "← Înapoi la meniu",
    },
    games: {
      hangmanTitle: "Ghicește cuvântul sau expresia",
      hangmanDesc: "Joc cu indicii, inimi și tastatură interactivă",
    },
    hangman: {
      restart: "Reia",
      random: "Aleator",
      import: "Importă",
      fullscreenEnter: "Tot ecranul",
      fullscreenExit: "Ieși",
      soundOn: "Pornit",
      soundOff: "Oprit",
      showPanels: "Arată panourile",
      hidePanels: "Ascunde panourile",
      clue: "Indiciu",
      try: "Încearcă",
      showSolution: "Arată soluția",
      hideSolution: "Ascunde soluția",
      letterPlaceholder: "Literă",
      longLetterPlaceholder: "Introdu o literă",
      errors: "Greșeli",
      won: "Câștigat",
      lost: "Pierdut",
      easy: "Ușor",
      medium: "Mediu",
      hard: "Dificil",
      hearts: "Inimi",
      addItemTitle: "Adaugă cuvânt sau expresie",
      itemPlaceholder: "Cuvânt sau expresie",
      cluePlaceholder: "Indiciu",
      addAndPlay: "Adaugă și joacă",
      archiveTitle: "Arhivă live",
      roundLabel: "Runda",
      hiddenSolution: "soluție ascunsă",
      liveGame: "Joc stil live",
      title: "Ghicește cuvântul sau expresia",
      downloadTemplate: "Descarcă șablonul",
      next: "Înainte",
    },
  },
  fr: {
    home: {
      title: "Jeux en direct",
      subtitle: "Choisissez un jeu et jouez avec votre communauté",
      languageLabel: "Langue",
      open: "Ouvrir",
      backToMenu: "← Retour au menu"
    },

    games: {
      hangmanTitle: "Jeu du pendu",
      hangmanDesc: "Devinez le mot ou la phrase avec l'aide de l'indice"
    },

    hangman: {
      title: "Devinez le mot ou la phrase",
      liveGame: "Jeu style live",
      clue: "Indice",
      hearts: "cœurs",

      easy: "Facile",
      medium: "Moyen",
      hard: "Difficile",

      errors: "Erreurs",
      won: "Gagné",
      lost: "Perdu",

      try: "Essayer",
      next: "Suivant",

      showSolution: "Afficher la solution",
      hideSolution: "Masquer la solution",

      restart: "Recommencer",
      random: "Aléatoire",
      import: "Importer",
      downloadTemplate: "Télécharger modèle",

      fullscreenEnter: "Plein écran",
      fullscreenExit: "Quitter",

      soundOn: "Son ON",
      soundOff: "Son OFF",

      showPanels: "Afficher panneaux",
      hidePanels: "Masquer panneaux",

      letterPlaceholder: "Lettre",
      longLetterPlaceholder: "Entrez une lettre",

      addItemTitle: "Ajouter mot ou phrase",
      itemPlaceholder: "Mot ou phrase",
      cluePlaceholder: "Indice",
      addAndPlay: "Ajouter et jouer",

      archiveTitle: "Archives live",
      roundLabel: "Manche",
      hiddenSolution: "solution cachée"
    }
  }
};