export const UI_TEXT = {
  it: {
    home: {
      title: "Live Games Hub",
      subtitle: "Scegli il gioco da usare in live",
      languageLabel: "Lingua",
      open: "Apri",
      backToMenu: "← Torna al menu",
    },
    games: {
      hangmanTitle: "Impiccato",
      hangmanDesc: "Indovina la parola o frase con un indizio",
      hangmanIcon: "🤖",
      hangmanIconBg: "from-emerald-400 to-lime-500",
      hangmanOverlay: "from-emerald-500/20 via-transparent to-lime-500/20",

      bersaglioTitle: "Il Bersaglio",
      bersaglioDesc: "Dalla parola esterna fino al centro: anagrammi, sinonimi, associazioni!",
      bersaglioIconBg: "from-yellow-400 to-orange-500",
      bersaglioOverlay: "from-yellow-500/20 via-transparent to-orange-500/20",

      numbergameTitle: "Indovina il Numero",
      numbergameDesc: "Più alto, più basso… trova il numero segreto!",
      numbergameIconBg: "from-orange-400 to-yellow-400",
      numbergameOverlay: "from-orange-500/20 via-transparent to-yellow-500/20",

      mastermindTitle: "Mastermind",
      mastermindDesc: "Indovina la combinazione di colori",
      mastermindIconBg: "from-violet-400 to-pink-500",
      mastermindOverlay: "from-violet-500/20 via-transparent to-pink-500/20",
      mastermindIconDots: ["bg-red-500", "bg-blue-500", "bg-green-500", "bg-yellow-400"],
    },
    hangman: {
      restart: "Ricomincia", random: "Casuale", import: "Importa",
      fullscreenEnter: "Full", fullscreenExit: "Esci",
      soundOn: "On", soundOff: "Off",
      showPanels: "Mostra pannelli", hidePanels: "Nascondi pannelli",
      clue: "Indizio", try: "Prova",
      showSolution: "Mostra soluzione", hideSolution: "Nascondi soluzione",
      letterPlaceholder: "Lettera", longLetterPlaceholder: "Inserisci una lettera",
      errors: "Errori", won: "Vinto", lost: "Perso",
      easy: "Facile", medium: "Media", hard: "Difficile", hearts: "Cuori",
      addItemTitle: "Aggiungi parola o frase", itemPlaceholder: "Parola o frase",
      cluePlaceholder: "Indizio", addAndPlay: "Aggiungi e gioca",
      archiveTitle: "Archivio live", roundLabel: "Round",
      hiddenSolution: "soluzione nascosta", liveGame: "Gioco stile live",
      title: "Indovina la parola o la frase", downloadTemplate: "Scarica template", next: "Avanti",
    },
    mastermind: {
      won: "Hai vinto 🎉", lost: "Hai perso 😈",
      solution: "Soluzione", next: "Avanti", colors: "Colori",
      correct: "colore e posizione giusti", present: "colore giusto, posizione sbagliata",
    },
    numbergame: {
      title: "Indovina il Numero", reset: "Reset",
      setupDesc: "Scegli il range dei numeri per questo round",
      from: "Da", to: "A", attemptsInfo: "Tentativi:",
      start: "🎲 Inizia il round!", range: "Range",
      won: "🎉 Trovato!", wonIn: "In", attempts: "tentativi",
      lost: "😈 Tempo scaduto!", solution: "Era il",
      nextRound: "Nuovo round", changeRange: "Cambia range",
    },
    bersaglio: {
      title: "Il Bersaglio", importBtn: "Importa",
      importError: "Errore nel file. Controlla il formato.",
      emptyTitle: "Nessun percorso caricato",
      emptyDesc: "Importa un file Excel con i tuoi percorsi",
      path: "Percorso", nextWord: "Prossima parola",
      findCenter: "Trova la parola centrale!", letters: "lettere",
      wrong: "Non è quella! Riprova...", won: "Bersaglio centrato!",
      nextPath: "Prossimo percorso", inputPlaceholder: "Scrivi la parola...",
      startFrom: "Parti da",
      nextFrom: "Collegata a",
      legendStart: "Partenza",
      legendEnd: "Bersaglio",
      legendUsed: "Già usata",
      lost: "💔 Cuori esauriti!",
      solutionLabel: "Il percorso corretto era",
    },
  },

  en: {
    home: {
      title: "Live Games Hub",
      subtitle: "Choose the game to use on live",
      languageLabel: "Language", open: "Open", backToMenu: "← Back to menu",
    },
    games: {
      hangmanTitle: "Hangman",
      hangmanDesc: "Guess the word or phrase with a clue",
      hangmanIcon: "🤖",
      hangmanIconBg: "from-emerald-400 to-lime-500",
      hangmanOverlay: "from-emerald-500/20 via-transparent to-lime-500/20",

      bersaglioTitle: "The Target",
      bersaglioDesc: "From the outer word to the center: anagrams, synonyms, associations!",
      bersaglioIconBg: "from-yellow-400 to-orange-500",
      bersaglioOverlay: "from-yellow-500/20 via-transparent to-orange-500/20",

      numbergameTitle: "Guess the Number",
      numbergameDesc: "Higher, lower… find the secret number!",
      numbergameIconBg: "from-orange-400 to-yellow-400",
      numbergameOverlay: "from-orange-500/20 via-transparent to-yellow-500/20",

      mastermindTitle: "Mastermind",
      mastermindDesc: "Guess the color combination",
      mastermindIconBg: "from-violet-400 to-pink-500",
      mastermindOverlay: "from-violet-500/20 via-transparent to-pink-500/20",
      mastermindIconDots: ["bg-red-500", "bg-blue-500", "bg-green-500", "bg-yellow-400"],
    },
    hangman: {
      restart: "Restart", random: "Random", import: "Import",
      fullscreenEnter: "Full", fullscreenExit: "Exit",
      soundOn: "On", soundOff: "Off",
      showPanels: "Show panels", hidePanels: "Hide panels",
      clue: "Clue", try: "Try",
      showSolution: "Show solution", hideSolution: "Hide solution",
      letterPlaceholder: "Letter", longLetterPlaceholder: "Enter a letter",
      errors: "Errors", won: "Won", lost: "Lost",
      easy: "Easy", medium: "Medium", hard: "Hard", hearts: "Hearts",
      addItemTitle: "Add word or phrase", itemPlaceholder: "Word or phrase",
      cluePlaceholder: "Clue", addAndPlay: "Add and play",
      archiveTitle: "Live archive", roundLabel: "Round",
      hiddenSolution: "hidden solution", liveGame: "Live style game",
      title: "Guess the word or phrase", downloadTemplate: "Download template", next: "Next",
    },
    mastermind: {
      won: "You won 🎉", lost: "You lost 😈",
      solution: "Solution", next: "Next", colors: "Colors",
      correct: "correct color and position", present: "correct color, wrong position",
    },
    numbergame: {
      title: "Guess the Number", reset: "Reset",
      setupDesc: "Choose the number range for this round",
      from: "From", to: "To", attemptsInfo: "Attempts:",
      start: "🎲 Start the round!", range: "Range",
      won: "🎉 Found it!", wonIn: "In", attempts: "attempts",
      lost: "😈 Time's up!", solution: "It was",
      nextRound: "Next round", changeRange: "Change range",
    },
    bersaglio: {
      title: "The Target", importBtn: "Import",
      importError: "File error. Check the format.",
      emptyTitle: "No paths loaded",
      emptyDesc: "Import an Excel file with your paths",
      path: "Path", nextWord: "Next word",
      findCenter: "Find the central word!", letters: "letters",
      wrong: "Not that one! Try again...", won: "Target hit!",
      nextPath: "Next path", inputPlaceholder: "Type the word...",
      startFrom: "Start from",
      nextFrom: "Connected to",
      legendStart: "Start",
      legendEnd: "Target",
      legendUsed: "Already used",
      lost: "💔 No hearts left!",
      solutionLabel: "The correct path was",
    },
  },

  ro: {
    home: {
      title: "Hub Jocuri Live",
      subtitle: "Alege jocul pentru live",
      languageLabel: "Limbă", open: "Deschide", backToMenu: "← Înapoi la meniu",
    },
    games: {
      hangmanTitle: "Ghicește cuvântul",
      hangmanDesc: "Joc cu indicii, inimi și tastatură interactivă",
      hangmanIcon: "🤖",
      hangmanIconBg: "from-emerald-400 to-lime-500",
      hangmanOverlay: "from-emerald-500/20 via-transparent to-lime-500/20",

      bersaglioTitle: "Ținta",
      bersaglioDesc: "De la cuvântul exterior până la centru: anagrame, sinonime, asociații!",
      bersaglioIconBg: "from-yellow-400 to-orange-500",
      bersaglioOverlay: "from-yellow-500/20 via-transparent to-orange-500/20",

      numbergameTitle: "Ghicește Numărul",
      numbergameDesc: "Mai mare, mai mic… găsește numărul secret!",
      numbergameIconBg: "from-orange-400 to-yellow-400",
      numbergameOverlay: "from-orange-500/20 via-transparent to-yellow-500/20",

      mastermindTitle: "Mastermind",
      mastermindDesc: "Ghicește combinația de culori",
      mastermindIconBg: "from-violet-400 to-pink-500",
      mastermindOverlay: "from-violet-500/20 via-transparent to-pink-500/20",
      mastermindIconDots: ["bg-red-500", "bg-blue-500", "bg-green-500", "bg-yellow-400"],
    },
    hangman: {
      restart: "Reia", random: "Aleator", import: "Importă",
      fullscreenEnter: "Tot ecranul", fullscreenExit: "Ieși",
      soundOn: "Pornit", soundOff: "Oprit",
      showPanels: "Arată panourile", hidePanels: "Ascunde panourile",
      clue: "Indiciu", try: "Încearcă",
      showSolution: "Arată soluția", hideSolution: "Ascunde soluția",
      letterPlaceholder: "Literă", longLetterPlaceholder: "Introdu o literă",
      errors: "Greșeli", won: "Câștigat", lost: "Pierdut",
      easy: "Ușor", medium: "Mediu", hard: "Dificil", hearts: "Inimi",
      addItemTitle: "Adaugă cuvânt sau expresie", itemPlaceholder: "Cuvânt sau expresie",
      cluePlaceholder: "Indiciu", addAndPlay: "Adaugă și joacă",
      archiveTitle: "Arhivă live", roundLabel: "Runda",
      hiddenSolution: "soluție ascunsă", liveGame: "Joc stil live",
      title: "Ghicește cuvântul sau expresia", downloadTemplate: "Descarcă șablonul", next: "Înainte",
    },
    mastermind: {
      won: "Ai câștigat 🎉", lost: "Ai pierdut 😈",
      solution: "Soluție", next: "Următor", colors: "Culori",
      correct: "culoare și poziție corecte", present: "culoare corectă, poziție greșită",
    },
    numbergame: {
      title: "Ghicește Numărul", reset: "Reset",
      setupDesc: "Alege intervalul de numere pentru această rundă",
      from: "De la", to: "La", attemptsInfo: "Încercări:",
      start: "🎲 Începe runda!", range: "Interval",
      won: "🎉 Găsit!", wonIn: "În", attempts: "încercări",
      lost: "😈 Timp expirat!", solution: "Era",
      nextRound: "Rundă nouă", changeRange: "Schimbă intervalul",
    },
    bersaglio: {
      title: "Ținta", importBtn: "Importă",
      importError: "Eroare în fișier. Verificați formatul.",
      emptyTitle: "Niciun traseu încărcat",
      emptyDesc: "Importați un fișier Excel cu traseele dvs.",
      path: "Traseu", nextWord: "Cuvântul următor",
      findCenter: "Găsiți cuvântul central!", letters: "litere",
      wrong: "Nu e ăla! Încearcă din nou...", won: "Țintă atinsă!",
      nextPath: "Traseu următor", inputPlaceholder: "Scrie cuvântul...",
      startFrom: "Pornește de la",
      nextFrom: "Conectat la",
      legendStart: "Start",
      legendEnd: "Țintă",
      legendUsed: "Deja folosit",
      lost: "💔 Fără inimi!",
      solutionLabel: "Traseul corect era",
    },
  },

  fr: {
    home: {
      title: "Jeux en direct",
      subtitle: "Choisissez un jeu et jouez avec votre communauté",
      languageLabel: "Langue", open: "Ouvrir", backToMenu: "← Retour au menu",
    },
    games: {
      hangmanTitle: "Jeu du pendu",
      hangmanDesc: "Devinez le mot ou la phrase avec l'aide de l'indice",
      hangmanIcon: "🤖",
      hangmanIconBg: "from-emerald-400 to-lime-500",
      hangmanOverlay: "from-emerald-500/20 via-transparent to-lime-500/20",

      bersaglioTitle: "La Cible",
      bersaglioDesc: "Du mot extérieur jusqu'au centre : anagrammes, synonymes, associations !",
      bersaglioIconBg: "from-yellow-400 to-orange-500",
      bersaglioOverlay: "from-yellow-500/20 via-transparent to-orange-500/20",

      numbergameTitle: "Devine le Nombre",
      numbergameDesc: "Plus haut, plus bas… trouve le nombre secret !",
      numbergameIconBg: "from-orange-400 to-yellow-400",
      numbergameOverlay: "from-orange-500/20 via-transparent to-yellow-500/20",

      mastermindTitle: "Mastermind",
      mastermindDesc: "Devinez la combinaison de couleurs",
      mastermindIconBg: "from-violet-400 to-pink-500",
      mastermindOverlay: "from-violet-500/20 via-transparent to-pink-500/20",
      mastermindIconDots: ["bg-red-500", "bg-blue-500", "bg-green-500", "bg-yellow-400"],
    },
    hangman: {
      restart: "Recommencer", random: "Aléatoire", import: "Importer",
      fullscreenEnter: "Plein écran", fullscreenExit: "Quitter",
      soundOn: "Son ON", soundOff: "Son OFF",
      showPanels: "Afficher panneaux", hidePanels: "Masquer panneaux",
      clue: "Indice", try: "Essayer",
      showSolution: "Afficher la solution", hideSolution: "Masquer la solution",
      letterPlaceholder: "Lettre", longLetterPlaceholder: "Entrez une lettre",
      errors: "Erreurs", won: "Gagné", lost: "Perdu",
      easy: "Facile", medium: "Moyen", hard: "Difficile", hearts: "Cœurs",
      addItemTitle: "Ajouter mot ou phrase", itemPlaceholder: "Mot ou phrase",
      cluePlaceholder: "Indice", addAndPlay: "Ajouter et jouer",
      archiveTitle: "Archives live", roundLabel: "Manche",
      hiddenSolution: "solution cachée", liveGame: "Jeu style live",
      title: "Devinez le mot ou la phrase", downloadTemplate: "Télécharger modèle", next: "Suivant",
    },
    mastermind: {
      won: "Vous avez gagné 🎉", lost: "Vous avez perdu 😈",
      solution: "Solution", next: "Suivant", colors: "Couleurs",
      correct: "couleur et position correctes", present: "couleur correcte, mauvaise position",
    },
    numbergame: {
      title: "Devine le Nombre", reset: "Reset",
      setupDesc: "Choisissez la plage de nombres pour ce round",
      from: "De", to: "À", attemptsInfo: "Essais :",
      start: "🎲 Commencer le round !", range: "Plage",
      won: "🎉 Trouvé !", wonIn: "En", attempts: "essais",
      lost: "😈 Temps écoulé !", solution: "C'était le",
      nextRound: "Nouveau round", changeRange: "Changer la plage",
    },
    bersaglio: {
      title: "La Cible", importBtn: "Importer",
      importError: "Erreur dans le fichier. Vérifiez le format.",
      emptyTitle: "Aucun parcours chargé",
      emptyDesc: "Importez un fichier Excel avec vos parcours",
      path: "Parcours", nextWord: "Mot suivant",
      findCenter: "Trouvez le mot central !", letters: "lettres",
      wrong: "Ce n'est pas ça ! Réessayez...", won: "Cible atteinte !",
      nextPath: "Parcours suivant", inputPlaceholder: "Écrivez le mot...",
      startFrom: "Partez de",
      nextFrom: "Connecté à",
      legendStart: "Départ",
      legendEnd: "Cible",
      legendUsed: "Déjà utilisé",
      lost: "💔 Plus de cœurs !",
      solutionLabel: "Le parcours correct était",
    },
  },
};
